<a href="https://colab.research.google.com/github/eunyeongkimm/nlp_hierarchical_game_review_absa/blob/main/%EA%B8%B0%EA%B3%84%ED%95%99%EC%8A%B5%ED%8A%B9%EB%A1%A0_2%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C_2025713060_%EA%B9%80%EC%9D%80%EC%98%81.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
## import 라이브러리(코드의 묶음) 불러오기.
# as(~로) np라고 불러오자
## numpy.~~~   ->  np.~~~ 로 하자고 약속

- 상기 셀에서는 파이썬의 "numpy("넘파이"라고 발음)" 라이브러리를 "np"라는 이름으로 불러온다.
- Numpy 라이브러리는 기계학습 관련 코드에서 거의 항상/반드시 사용되는 수학 함수(배열에 대한 다양한 수학 연산이 가능함) 라이브러리이므로 기계학습 관련 코딩을 할 때는 제일 먼저 numpy 라이브러리를 불러오도록 하자.
[Numpy 공식 도큐먼트 사이트](https://numpy.org/doc/stable/user/absolute_beginners.html)
- 참고: 라이브러리란?
        - 라이브러리 : 여러 패키지와 모듈을 모아놓은 것
            - 패키지 : 특정 기능과 관련된 여러 모듈이 모여있는 한 폴더
            - 모듈 : 여러가지 함수, 변수 등을 모아 놓은 것

In [2]:
from google.colab import drive
drive.mount('/content/drive')
# 왼쪽배너에서 폴더 모양을 클릭 후 드라이브 마운트를 통해서 코랩에 업로드한 파일을
# 구글 드라이브에서 검색할 수 있다.
# (파일-드라이브에 사본 저장)기능에서 기본 저장되는 폴더는 "/content/drive/colab notebook" 이다.

Mounted at /content/drive


array, dimension, arrange, shape, reshape, indexing, slicing, stack, concatenation.
- /+ dot, matmul, transpose 도 추가로 공부해보자.


In [3]:
def print_obj(obj, name):
    print("%s:\n%s\n" % (name, obj))
    ## definition -> 함수를 정의합니다.
    ## name, obj 변수 두개를 할당(assign)해서 함수를 정의(def)해봅시다.
    ## 첫번째 %s -> name, 두번째 %s -> obj // \n -> 엔터해서 출력
    ## 첫번째랑 두번째를 구분하는 콜론 :
    # 포맷팅 -> 3가지 방법 : % 포맷팅, format 포맷팅, printf()

def check_each(a, b):
    return (a == b).astype('bool')
## booliean 불리언 타입 : 참이냐 거짓이냐 true, false?? 검사.
## == 동일한가? 조건문!에 의한 함수 정의

def check_mean(a, b):
    return np.mean(a == b).astype('bool')

## a,b의 성분들의 각각의 평균 mean이 동일한가?? 조건문! 참이면 True, 거짓이면 False를 뱉어!

- 위의 코드에서는 실습 과정에서 계속 사용될 함수를 정의하였다.
- "print_obj"는 출력하려는 객체(object) "이름"과 객체가 실제 저장하는 내용(값)을 출력하는 역할을 한다.
    - cf. escape 이스케이프 코드 : \n - 문자열 안에서 줄을 바꿀 때 사용
    - cf. 포맷팅(Formatting) : 문자열안에 특정부분을 특정 변수의 위치로 정해줌으로써 해당 변수의 값에 따라 문자열 자체가 변경 될 수 있게 하는 기능
        - 3가지 방법 : % 포맷팅, format 포맷팅, printf()
        - (문자열 포맷 코드) %s : 문자열(String)
- check_each와 check_mean은 참과 거짓을 판별하는 불리언 타입의 함수를 정의한 것이다.

*** cf. 파이썬에서 사용되는 주요 데이터 타입**

<img src="https://pynative.com/wp-content/uploads/2021/02/python-data-types.jpg" width="500" height="400" alt="파이썬의 주요 데이터 타입" />


In [4]:
    obj = 1
    print_obj(obj,"name")

name:
1



### 스칼라(Scalars), 벡터(Vectors), 행렬(Matrices)

In [5]:
a = np.array(1.)   # 0차원 배열  ## np. 어레이!!
## 1과 1. 이 다른 점 : 정수냐 실수냐? .점이 붙으면 실수 타입 표현이다.
b = np.array([1., 2., 3.])  # 1차원 배열
c = np.array([[1., 2., 3.], [4., 5., 6.]])  # 2차원 배열

## 0 ~ 2 차원 까지 우리가 배웠지만,
## 앞으로는 N차원의 배열을 N차원의 텐서! 라고 부른다.
## a,b,c 변수가 왼쪽 // 변수에 할당되는 값이 오른쪽.
## 할당된 상태일뿐, 출력하려면 print를 써야한다.

- 향후 실습에서 사용될 a, b, c값을 로드해보자. print로 실행을 해야 해당 값이 로드(출력)됨에 유의.
    - 주의 : numpy 라이브러리를 사용하기 전에는 리스트를 기본 자료형으로 사용했을 것이다. 그런데 numpy에서는 배열처리를 위하여 ndarray라는 새로운 개체를 제공한다(현 수준에서는 벡터를 처리하기 위해 편리한 자료형 정도의 수준으로 ndarray를 이해하여도 충분).
- "np.array"라는 짧은 명령어에는 "numpy 라이브러리의 array()함수를 불러다 사용한다"라는 긴 내용이 축약되어 있다.
- 먼저 numpy 라이브러리를 "np"라고 불러왔음을 상기하자. "np.array"에서 "."은 numpy가 가지고 있는 다양한 함수를 불러오라는 명령을 전달하며 "np.array"라고 표현하면 numpy가 가지고 있는 다양한 명령 중에서도 array()함수를 불러오라는 의미를 갖는다.
- "b = np.array([1., 2., 3.])"라는 명령을 통해 1.0, 2.0, 3.0의 세 개의 값을 갖는 1차원 배열 "b"를 만들었다.
"c"는 세 개의 값을 갖는 1차원 배열 2개가 모인 2차원 배열을 의미한다.

- "check_each"와 "check_mean"에서는 ".astype('bool')"이라는 표현이 존재한다. 이 때 "astype"은 ndarray에 저장된 데이터값의 타입을 변경하는 역할을 하는데, 이 코드에서는 "bool"이라는 타입으로 변경한다.

In [6]:
print(a, b, c, sep = "\n\n")
# print(a)
# print(b)
# print(c)

1.0

[1. 2. 3.]

[[1. 2. 3.]
 [4. 5. 6.]]


In [7]:
print_obj(a, "a")  ## 함수를 예쁘게 짜놓고 언제든 써먹는다. : def function
print_obj(b, "b")
print_obj(c, "c")

a:
1.0

b:
[1. 2. 3.]

c:
[[1. 2. 3.]
 [4. 5. 6.]]



In [8]:
a.ndim

0

In [9]:
print_obj(a.ndim, "a.ndim")  ## .dim  : 디멘젼 dimension
## 차원의 크기!! N차원의 크기 -> ndim 함수 // 쓰는법 : 변수.함수
print_obj(b.ndim, "b.ndim")
print_obj(c.ndim, "c.ndim")

## 0차원 텐서  1차원 텐서  2차원 텐서
## 0차원 배열  1차원 배열  2차원 배열
## 앞으로는 텐서와 배열이라는 용어로 다차원(수많은 카테고리)의 데이터를 표현하자.

a.ndim:
0

b.ndim:
1

c.ndim:
2



- "a.ndim"은 배열의 차원의 수를 알려주는 기능을 한다.
- 상기 코드를 실행한 후 ndim의 출력값을 이해하고자 시도해 보자. 구글링을 통해 1차원 배열, 2차원 배열에 대하여 공부하면 ndim의 기능이 이해가 될 것이다.

In [10]:
print_obj(a.shape, "a.shape") ## 배열의 모양 // . shape
## 배열의 모양? 몇 바이 몇??
print_obj(b.shape, "b.shape")
print_obj(c.shape, "c.shape")
d = np.array([[1,2,3]]) ## [] 첫번째 차원, [[]] 두번째 차원,  (첫번째차원)by(두번째차원) 행렬,
## 1by3행렬, 차원을 구분할때 대괄호 개수로 구분하자!
print_obj(d.shape, "d.shape") #행렬 안에 행렬


# [1,2,3] --> (3,)
# [[1,2,3]] --> (1,3) :: 1행 3열짜리 행렬

a.shape:
()

b.shape:
(3,)

c.shape:
(2, 3)

d.shape:
(1, 3)



- "shape"는 배열의 모양(배열의 모양(shape)은 각 차원에 존재하는 요소(값)의 수를 의미)을 알려준다.
    - "a"는 1개의 요소로만 구성되어 아무 값도 표시되지 않으나 3개의 요소로 구성된 "b"의 출력값 "(3,)"은 3개의 행으로 b가 표시되고 있음을 알려준다. "c"의 출력인 "(2,3)"은 행은 2개, 열은 3개 있는 형태로 c가 표시됨을 알려준다.
- "b"와 "d"는 어떤 차이가 있길래 결과가 틀릴까?
    - np.array([1,2,3])이라고 표현하면 행의 갯수 3만 반환하지만,np.array([[1,2,3]])로 표현하면 1개의 행과 3개의 열로 구성된 행렬의 모양을 반환한다.  

### 텐서(Tensors) (N-dimensional array)

In [11]:
d = np.array([[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]]])
# 대괄호 3개 있으니까 3차원., 대괄호 개수 3개이상 텐서!! N개의 대괄호 : N차원 텐서다!
# 텐서로 배열을 전부 표현 가능.
e = np.array([[[[1., 2., 3.], [1., 2., 3.]], [[4., 5., 6.], [4., 5., 6.]]],
              [[[7., 8., 9.], [7., 8., 9.]], [[10., 11., 12.], [10., 11., 12.]]]])
# 대괄호 4개 4차원.

In [12]:
print_obj(d, "d")
print_obj(d.ndim, "d.ndim")
print_obj(d.shape, "d.shape")

print_obj(e, "e")
print_obj(e.ndim, "e.ndim")
print_obj(e.shape, "e.shape")


d:
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]

d.ndim:
3

d.shape:
(2, 2, 3)

e:
[[[[ 1.  2.  3.]
   [ 1.  2.  3.]]

  [[ 4.  5.  6.]
   [ 4.  5.  6.]]]


 [[[ 7.  8.  9.]
   [ 7.  8.  9.]]

  [[10. 11. 12.]
   [10. 11. 12.]]]]

e.ndim:
4

e.shape:
(2, 2, 2, 3)



- 스칼라 값은 0차원 텐서, 벡터는 1차원 텐서, 행렬은 2차원 텐서, 행렬의 배열은 3차원 텐서, 3차원 텐서의 배열(행렬의 배열의 배열)은 4차원 텐서이다.
- N차원 텐서란 무엇인지 알아보자.

In [13]:
# 퀴즈 1 : [[[1], [2], [3]], [[4], [5], [6]]]의 shape는 어떻게 되는가? *shape를 알아낼 수 있는 코드를 작성하여 본인의 답을 확인해보자!
q1 = np.array([[[1], [2], [3]], [[4], [5], [6]]])
print_obj(q1.shape, "q1.shape")

## 3행 1열 행렬이 2개가 겹쳐진 구조임(행 단위로 [ ]가 생기는 것임)

q1.shape:
(2, 3, 1)



### 넘파이 배열 정의 (Defining Numpy arrays)

In [14]:
a = np.ones(10)
a
## one 1이니까. ones라는 넘파이 안에 함수가
## 1이라는 성분으로 (10)개 만큼 배열을 만들어 주세요.
# 실수형태로 들어가네!? 아하.
# 1.0 1.0 1.0 ~~~(실수형태)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
a = np.zeros((2, 5))
a
### zero 0이니까. 0이라는 성분으로 (2*5)개 만큼 배열을 만들어 주세요.
# 2 - by - 5 행렬형태
# 실수형태로 들어가네!? 아하.
# a = np.zeros((5, 2))
# a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
a = np.full((2,5), 5)  ## 2바이5 행렬, 안에 5라는 성분(element)을 full

# full((배열의모양),들어갈숫자)
# 5를 2바이5 배열로 만들어주세요. 채워주세요.
a


array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [17]:
t = np.full((1,1,1), -1)
print(t)
print(t.ndim)
print(t.shape)

[[[-1]]]
3
(1, 1, 1)


In [18]:
a = np.random.random((2, 3, 4))  ## 랜덤함수 -> 임의의 숫자
a
## 랜덤 실행할때마다 랜덤 숫자를 (소숫점 8째자리까지 보임. 실수형태)
## np.random.random(배열의모양)
## np.random 모듈 안의 random 함수 / 자매품 np.random.randint(0, 10)

array([[[0.32650641, 0.34628064, 0.71088589, 0.01198034],
        [0.91149946, 0.97448194, 0.55881831, 0.59333763],
        [0.69181191, 0.56820969, 0.02903519, 0.31477448]],

       [[0.66936345, 0.34944696, 0.59124428, 0.00189364],
        [0.35356977, 0.88611896, 0.39719425, 0.61009197],
        [0.58069189, 0.65295462, 0.00711772, 0.06104272]]])

In [19]:
np.random.randint(0, 10)

6

In [20]:
a = np.arange(10)  ## 숫자 배열 생성 np.arrange()  ## 0부터 시작!!
a
## 컴퓨터는 항상 0부터!! 중요!!
## 10개짜리 배열을 생성해주세요. np.arrange
## 정수형태

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a = np.arange(10).astype(float)
a
#astype을 사용하여 "float"(실수) 자료형으로 a를 구성
#integer(int) : 정수
#아스키코드 : 형태를 지정
#실수는 0. 이렇게 표현 : 실제로는 : 0.0, 1.0, 2.0, 3.0, 4.0, ~~~, ,9.0

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
a = np.arange(10).reshape((5,2))  ## reshape 기능!!! 1차원 배열을 2차원 5 by 2 형태로
## 중요. 배열을 원하는 모양으로 바꿔서 만들자!!
# b = np.arange(10).reshape((5,1)) ## 에러
a  ## 5바이2 배열 형태를 출력, 들어갈 숫자가 (0 ~ 9) 10개 숫자를 넣음.

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [23]:
# 퀴즈 2: (4,3,2) 텐서를 만들고 0부터 23 숫자로 채우시오 (Create a 4-by-3-by-2 tensor filled with 0.0 to 23.0)

# 힌트 . 4*3*2 = 24 // 24개 숫자 : 0 ~ 23까지죠.

q2 = np.arange(24).astype(float).reshape((4,3,2))
print_obj(q2.shape, "q2.shape")
print('\n', q2)

q2.shape:
(4, 3, 2)


 [[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]]

 [[ 6.  7.]
  [ 8.  9.]
  [10. 11.]]

 [[12. 13.]
  [14. 15.]
  [16. 17.]]

 [[18. 19.]
  [20. 21.]
  [22. 23.]]]


### 인덱스 (Indexing) & 슬라이싱 (Slicing)

In [24]:
# 벡터의 인덱스와 슬라이싱 (Indexing and slicing a vector)
## 중요!!!
a = np.arange(10)
print_obj(a, "a")
# a: // 인덱스란? : (사전에서) 의미가 목차, 순서, 색인 : 한마디로 몇번째냐?
# [0 1 2 3 4 5 6 7 8 9]
## 인덱스 -> 변수[몇번째]로 숫자를 찾아온다.
print_obj(a[0], "a[0]") ## 0 (0번째)
print_obj(a[1], "a[1]")  ## 1 (1번쨰)
print_obj(a[-1], "a[-1]")  ## 9 (뒤에서 첫번째)
print_obj(a[-3], "a[-3]")  ## 7 (뒤에서 3번째)

a:
[0 1 2 3 4 5 6 7 8 9]

a[0]:
0

a[1]:
1

a[-1]:
9

a[-3]:
7



In [25]:

## 콜론 -> 범위, 그래서 변수[몇번째:몇번째]로 뭐부터 뭐까지!! 찾아오세요.
# 아래 5가지는 전부 동일하다.
print_obj(a[0:10], "a[0:10]") ## : 콜론 -> 0 ~ 9까지
# 0이상 10 미만!! 0<= <10
print_obj(a[0:], "a[0:]") ## : 0 ~ 무한대  0번째 이상
print_obj(a[:],"a[:]") ## 인덱스 전부 포함. 그자체! ## 무한대 ~ 무한대 다포함!!
print_obj(a[:10], "a[:10]") ## 인덱스 10 미만(인덱스는 0번째부터 9번쨰까지 있는 상황임)
#print_obj(a[::1], "a[::1]")

print_obj(a[7:], "a[7:]")  ## 7번째 이상
print_obj(a[:5], "a[:5]")  ## 5번째 미만
print_obj(a[2:5], "a[2:5]")  ## 2번째 이상 5번째 미만

a[0:10]:
[0 1 2 3 4 5 6 7 8 9]

a[0:]:
[0 1 2 3 4 5 6 7 8 9]

a[:]:
[0 1 2 3 4 5 6 7 8 9]

a[:10]:
[0 1 2 3 4 5 6 7 8 9]

a[7:]:
[7 8 9]

a[:5]:
[0 1 2 3 4]

a[2:5]:
[2 3 4]



In [26]:
# 음수 인덱스 참고
#a = [10, 20, 30, 40, 50, 60, 70, 80]
#     0   1   2   3   4   5   6   7   ← 양수 인덱스
#    -8  -7  -6  -5  -4  -3  -2  -1   ← 음수 인덱스

In [27]:
# 퀴즈 3: a[-4:]는 무엇인가?  ## 뒤에서 4번째부터 끝까지
print_obj(a[-4:], "a[-4:]")

a[-4:]:
[6 7 8 9]



In [28]:
# 퀴즈 4: a[:-8]는 무엇인가?  ## 해보세요!! ## 뒤에서 8번째까지
print_obj(a[:-8], "a[:-8]")

a[:-8]:
[0 1]



In [29]:
## 콜론콜론 두번째 콜론 뒤에 숫자! : 스텝
print_obj(a[0:10:2], "a[0:10:2]") ## 0,2,4,6,8
print_obj(a[0:10:3], "a[0:10:3]") # 3스텝
print_obj(a[2:6:3], "a[2:6:3]") ##

## 스텝이 -1이면 역방향!
print_obj(a[::-1], "a[::-1]") ## 중요!!! 거꾸로!! 순서를 9 8 7 ~~~
print_obj(a[8:5:-1], "a[8:5:-1]")
print_obj(a[8:5], "a[8:5]") ## 8번째에서 5번째까지 순방향으로 도달 불가라서 빈 배열 return



a[0:10:2]:
[0 2 4 6 8]

a[0:10:3]:
[0 3 6 9]

a[2:6:3]:
[2 5]

a[::-1]:
[9 8 7 6 5 4 3 2 1 0]

a[8:5:-1]:
[8 7 6]

a[8:5]:
[]



In [30]:
# 퀴즈 5 : a를 이용하여 [9, 6, 3]를 생성하시오.
print_obj(a[9:2:-3], "a[9:2:-3]")

a[9:2:-3]:
[9 6 3]



In [31]:
print_obj(a[:-8], "a[:-8]")
## 인덱싱이 헷갈릴 수 있지만 익숙해지자!

a[:-8]:
[0 1]



**인덱싱**
- 행렬의 인덱싱을 이해하기 위해서는 인덱스 번호와 저장 순서의 차이를 이해하여야 한다.
    - 예를 들어 [a, b, c, d]의 4개의 값이 들어있는 리스트의 첫번째 저장요소는 a, 두 번째 저장요소는 b, 세번째 저장요소는 c이다.
    - 그런데 인덱스라는 개념을 사용할 때는 첫번째 저장요소의 인덱스는 0, 두번째 저장요소의 인덱스는 1, i번째 저장요소의 인덱스는 i-1이다.

**슬라이싱**

- ":"연산자를 이용한 인덱싱을 슬라이싱이라고 한다. 그런데 a[2:5]의 실행 결과를 살펴보자.
    - 실제 반환된 값의 인덱스와 2:5는 어떤 관계에 있는가? a[2:5]를 실행하면 [2, 3, 4]가 반환되는데 반환된 2는 a의 세번째 값이므로 인덱스는 2(세번째 값), 반한된 3은 인덱스가 3(네번째 값), 반환된 4는 인덱스가 4(다섯번째 값)에 해당하는 값들이다.
    - 그렇다면 "a[2:5]"라는 표현은 어떤 명령을 내리고 있다고 생각되는가? 2:5는 반환할 값들의 시작인덱스(2)와 종료인덱스(4)를 표현해야 하므로, 슬라이싱에서 **":"의 앞의 값이 시작인덱스, ":"뒤의 값-1이 종료 인덱스를 의미**한다고 정리할 수 있다.

- 슬라이싱 기호의 시작 인덱스와 종료 인덱스는 생략이 가능하다.

    1.  ":"기호 앞에 시작 인덱스를 생략하면 자동으로 시작 인덱스인 0으로 간주
    2.   ":" 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주
    3.   ":" 기호 앞 뒤를 모두 생략하면 시작부터 끝

**"-k"의 효과**

- "a[-3]"의 출력 결과는 어떻게 해석할 수 있을까? a[-3]은 7을 출력하는데 7은 8번째 숫자 혹은 인덱스 7에 해당하는 값이다.
- 따라서 인덱싱에서 "-k"는 "원소의 갯수 - k"의 인덱스에 해당하는 값을 나타낸다고 해석할 수 있다. "-k"가 ":"기기호의 뒤에서 사용될 때는 "원소의 개수 -k - 1"의 인덱스를 표시하는 것에 주의

**간격의 부여**

- 파이썬 슬라이싱에서 ":"기호가 2개 사용되는 경우는 인덱스에 간격을 부여하는 경우이다. "a[0:10:2]"와 "a[2:6:3]"의 동작 결과를 통해 간격의 동작을 추정해보자.
- 결과적으로는 "시작인덱스:종료값:간격"으로 명령이 전달됨을 알 수 있다.간격을 부여할 때는 "음의 간격"을 부여할 수도 있다.

**음의 간격을 부여할 때는**
1. "시작인덱스:종료값:**음수**"의 형태로 표시됨에 주의해야 하며
2. "종료값"과 반환된 값의 인덱스사이의 관계에 주의하여야 한다.
- 어떤 관계가 존재하는가? 종료값 +1이 실제 반환되는 값의 인덱스이다.

In [53]:
# 행렬의 인덱스 (Indexing a matrix)
a = np.arange(9).reshape((3,3))
print_obj(a, "a")
print_obj(a[0][0], "a[0][0]")
print_obj(a[0,0], "a[0,0]")
print_obj(a[1,1], "a[1,1]")


a:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

a[0][0]:
0

a[0,0]:
0

a[1,1]:
4



In [55]:
# 퀴즈 6: 마지막 행(row)을 어떻게 접근하는가?
print_obj(a[-1], "a[-1]")

a[-1]:
[6 7 8]



In [57]:
# 퀴즈 7: 두번째 열(column)을 어떻게 접근하는가?(Hint : 모든 행에서 2번째 저장된 값에 접근하면 된다. 모든 행을 표시하는 인덱싱 형태는 무엇일까?)

#일상 기준 2번째
print_obj(a[:,1], "a[:,1]")

#인덱스 기준 2번째
print_obj(a[:,2], "a[:,2]")

a[:,1]:
[1 4 7]

a[:,2]:
[2 5 8]



In [74]:
# 퀴즈 8: a를 이용해서 [8,5]를 생성하시오(Hint: 먼저 인덱싱을 이용하여 8, 5를 찾은 후 [8,5]형태로 출력할 방법을 고민해보자).
# a[행인덱스, 열인덱스] 형태로 쓴 것임
print_obj(a[[2,1], [2,2]], "a[[2,1], [2,2]]")

# 단순합산
print_obj(np.array([a[2,2], a[1,2]]), "np.array([a[2,2], a[1,2]])")

a[[2,1], [2,2]]:
[8 5]

np.array([a[2,2], a[1,2]]):
[8 5]



In [75]:
# 3차원 텐서의 인덱스와 슬라이싱(Indexing and slicing a 3D tensor)
a = np.arange(4*3*2).reshape((4, 3, 2))
print_obj(a, "a")
print_obj(a[2, 1, 0], "a[2, 1, 0]")
## 대괄호 개수로 인덱스를 잘 파악하자!

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

a[2, 1, 0]:
14



In [77]:
# 퀴즈 9: a[0]은 무엇인가?

## 0번째 행렬이 나온다
print_obj(a[0], "a[0]")

a[0]:
[[0 1]
 [2 3]
 [4 5]]



In [78]:
# 퀴즈 10: a[0, 1]은 무엇인가?

## 0번쨰 행렬의 1번째 행이 나온다
print_obj(a[0,1], "a[0,1]")

a[0,1]:
[2 3]



In [87]:
# 퀴즈 11: [[0, 2, 4], [6, 8, 10]] 를 생성하시오 (Hint : [0, 2, 4]는 무엇일까? [0,2,4]를 출력할 수 있는 방법은 무엇일까?).
print_obj(np.array([a[0][:,0], a[1][:,0]]), "[a[0][:,0], a[1][:,0]]")

## 더 간단한 방법
## :2는 앞에 두 행렬 선택, :는 모든행, 0은 첫번쨰 컬럼
print_obj(a[:2,:,0], "a[:2,:,0]")

[a[0][:,0], a[1][:,0]]:
[[ 0  2  4]
 [ 6  8 10]]

a[:2,:,0]:
[[ 0  2  4]
 [ 6  8 10]]



In [88]:
# 조건이 있는 인덱스 (Conditional indexing)
a = np.arange(3*2).reshape((3,2))
print_obj(a, "a")

idx = a % 2 == 0  ## 2로 나눈다. % 나누기, "==" 나머지 0
# 2로 나눴을때 0으로 떨어지는가? 나머지가 0인가?
## 조건문의 개념!!! 참True과 거짓False으로 출력 -> 조건문!!
print_obj(idx, "idx")


a:
[[0 1]
 [2 3]
 [4 5]]

idx:
[[ True False]
 [ True False]
 [ True False]]



In [91]:
# 퀴즈 12: a를 이용하여 [3, 4, 5] 를 생성하시오.

idx = a>=3
print_obj(a[idx], "a[idx]")

a[idx]:
[3 4 5]



**불리언 인덱싱**

- 불리언 인덱싱은 조건식을 이용한 인덱싱이다. 예를 들어 위의 코드에서는 "a%2==0"이라는 코드를 통해 a의 원소 중 2의 배수에 해당하는 원소를 검색하였다. 사실 idx에는 a%2==0을 만족하거나 만족하지 않는 원소에 대하여 True, False값이 저장된다(출력 결과 참조). 이제 "a[idx]"라는 명령을 사용하면 "a%2==0"에 해당하는 값이 출력된다. print(a[idx])의 결과를 확인해보자.

- 퀴즈 12의 경우 a의 원소 중 2보다 큰 값을 찾으면 된다. 따라서 예제 코드에서 idx가 2보다 큰 값에 대한 테스트 의미를 표시하도록 예제 코드를 변경하면 [3, 4, 5]를 생성할 수 있다.

In [92]:
# 벡터로 부터 특정 요소를 추출하는 것(Taking specific elements from a vector)
a = np.arange(10)
idx = [0, 2, 3]
idx2 = [1,2,3]

## 텐서의 성분의 위치를 변수로 idx로 지정해서
print_obj(a[idx], "a[idx]")

print_obj(a[idx2], "a[idx2]")

## 원하는 성분을 뽑아냈구나.

a[idx]:
[0 2 3]

a[idx2]:
[1 2 3]



In [93]:
# 텐서로 부터 특정 요소를 추출하는 것(Taking specific elements from a tensor)
a = np.arange(24).reshape((6,4))
print_obj(a, "a")

print_obj(a[:,[0, 2, 3]], "a[idx]")  ## 열 몇번째? 0,2,3번째 열의 성분들/  다가져와(콜론).
print_obj(a[[0, 2, 3], :], "a[idx]") ## 0,2,3번째 행의 성분들을 다 가져와.


a:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

a[idx]:
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]

a[idx]:
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]



In [98]:
## 심화.
idx = ((0,0,1,5),(1,2,0,3)) #0행1열, 0행2열, 1행0열, 5행3열
print_obj(a[idx], "tuple indexing")

idx = np.array([[0,0,1,5],[1,2,0,3]]) #[0행0행1행5행], [1행2행0행3행]
print_obj(a[idx], "ndarray indexing")
print_obj(a[idx].shape, "shape") # 2,4,4
## ndarray indexing은 행을 통째로 가져온다

idx_my = np.array([[0, 2, 1], [1, 2, 3]])
print_obj(a[idx_my],"a[idx_my]")
print_obj(a[idx_my].shape, "shape")

tuple indexing:
[ 1  2  4 23]

ndarray indexing:
[[[ 0  1  2  3]
  [ 0  1  2  3]
  [ 4  5  6  7]
  [20 21 22 23]]

 [[ 4  5  6  7]
  [ 8  9 10 11]
  [ 0  1  2  3]
  [12 13 14 15]]]

shape:
(2, 4, 4)

a[idx_my]:
[[[ 0  1  2  3]
  [ 8  9 10 11]
  [ 4  5  6  7]]

 [[ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]]

shape:
(2, 3, 4)



### 수학적 연산 (Math Operations)

In [99]:
# 기본 연산(Basic operations)
a = np.arange(6).reshape((3, 2))  ## 배열
b = np.ones((3, 2))  ## 3바이2 1로구성된 성분. 배열
print_obj(a, "a")
print_obj(b, "b")
## 넘파이 배열의 텐서들은 수학적 연산이 가능해진다.
# +, -, *, /
print_obj(a+b, "a+b")
print_obj(a-b, "a-b")
print_obj(a*b, "a*b")  # Hadamard product라고 함  ## 컴퓨터 학술용어.
print_obj(a/b, "a/b")

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

a+b:
[[1. 2.]
 [3. 4.]
 [5. 6.]]

a-b:
[[-1.  0.]
 [ 1.  2.]
 [ 3.  4.]]

a*b:
[[0. 1.]
 [2. 3.]
 [4. 5.]]

a/b:
[[0. 1.]
 [2. 3.]
 [4. 5.]]



- 행렬의 곱은 NXM의 행렬과 MXK의 행렬을 곱하면 NXK의 행렬이 산출되다고 학습하였을 것이다. 그렇다면 상기 예제의 코드는 어떤 곱셈을 하고 있을까?
- 상기 코드에서는 3X2 행렬과 3X2 행렬을 곱하는데, 이것은 2장에서 배운 행렬곱과 맞지 않는다.
- 실행 결과를 비교하면 금방 알 수 있지만 "*"기호와 "/"기호를 사용하면 동일한 크기의 행렬에 대하여 A[i,j]와 B[i,j]에 대하여 원소별로 곱하기를 하거나 나누기를 한 결과를 얻게 된다
**원소별로 곱하는 이런 연산을 Hadamard product라고 한다.성분의 동일한 위치끼리 곱하는 특별한 방법이다.*

- 2장에서 배운 행렬의 곱(NXM의 행렬과 MXK의 행렬을 곱하면 NXK의 행렬이 산출되는 경우)은 numpy의 matmul함수를 이용하거나 "@"연산자로 표현한다. **"@"연산자로 표현하는 행렬의 곱셈은 노트의 하단에 설명되어 있다. matmul도 함께 알아두자.*

In [100]:
# Unary 연산 (Unary operations)
a = np.arange(6).reshape((3,2))
print_obj(a, "a")

print_obj(a.sum(), "a.sum()") #summation. 축을 중심으로 성분을 더할 수 있다.
print_obj(a.sum(axis=0), "a.sum(axis=0)")  ## 축 axis 첫번째 축 0
print_obj(a.sum(axis=1), "a.sum(axis=1)")  ## 두번째 축 1

print_obj(a.mean(), "a.mean()") # 평균
print_obj(a.max(), "a.max()") # 최대
print_obj(a.min(), "a.min()") # 최소


a:
[[0 1]
 [2 3]
 [4 5]]

a.sum():
15

a.sum(axis=0):
[6 9]

a.sum(axis=1):
[1 5 9]

a.mean():
2.5

a.max():
5

a.min():
0



In [105]:
# 퀴즈 13: a = np.arange(24).reshape((2,3,4))가 주어졌을 때, 마지막 차원의 합의 평균은 얼마인가? (what is the mean of the sum w.r.t to the last dimension?)
# Hint : 퀴즈 13은 주어진 텐서에서 원하는 값들을 인덱싱한 후 mean()함수를 적용하면 된다.

a = np.arange(24).reshape((2,3,4))
print_obj(a.sum(axis = -1).mean(), "a.sum(axis = -1).mean()")

a.sum(axis = -1).mean():
46.0



In [106]:
# 벡터 내적(Vector dot product)
a = np.arange(3).astype('float')
b = np.ones(3)
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a, b), "a dot b")  ## 닷 프로덕트 : 내적 기능이 있다.

a:
[0. 1. 2.]

b:
[1. 1. 1.]

a dot b:
3.0



In [107]:
# 행렬 곱 연산 (Matrix dot product <-> matrix multiplication)
a = np.arange(6).reshape((3, 2))
b = np.ones((2, 3))
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a,b), "a dot b")
print_obj(a@b, "a @ b")   ## 골뱅이 행렬의 일반적인 곱셈!!
print_obj(np.matmul(a,b), "matmul(a,b)")   ## 맷뮬 행렬의 일반적인 곱셈!!

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[[1. 1. 1.]
 [1. 1. 1.]]

a dot b:
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]

a @ b:
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]

matmul(a,b):
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]



In [108]:
# 텐서 곱 연산 (Tensor dot product, tensor multiplication)
a = np.arange(24).reshape((4, 3, 2))
b = np.ones((4, 2, 3))
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a,b).shape, "a dot b")
print_obj((a@b).shape, "a @ b")  ## 골뱅이 행렬의 일반적인 곱셈!!
print_obj(np.matmul(a,b).shape, "matmul(a,b)")   ## 맷뮬 행렬의 일반적인 곱셈!!

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

b:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]

a dot b:
(4, 3, 4, 3)

a @ b:
(4, 3, 3)

matmul(a,b):
(4, 3, 3)



In [115]:
# 퀴즈 14: a.shape==(4,3,2) and b.shape==(2,3) 이라면, 곱셈 연산이 어떻게 되는가?
# Hint : 코드로 결과를 확인하여 보자.

a = np.arange(24).reshape((4,3,2))
b = np.arange(6).reshape((2,3))
print_obj(a, "a")
print_obj(b, "b")
print_obj(a @ b, "a@b")

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

b:
[[0 1 2]
 [3 4 5]]

a@b:
[[[  3   4   5]
  [  9  14  19]
  [ 15  24  33]]

 [[ 21  34  47]
  [ 27  44  61]
  [ 33  54  75]]

 [[ 39  64  89]
  [ 45  74 103]
  [ 51  84 117]]

 [[ 57  94 131]
  [ 63 104 145]
  [ 69 114 159]]]



- 1) *(=harmard), 2) dot, 3) @(=matmul) 은 서로 다른 연산이다.
우리는 일단 차이점이 있다는 것만 알아두자!

### 형태 변형 (Shape Manipulation)

In [116]:
# Reshapes
a = np.arange(24).reshape((2, 3, 4))
print_obj(a, "a")
## reshape 한거 한번 더!
b = a.reshape((6, 4))
print_obj(b, "b")

c = a.reshape((6, -1)) #-1하면 남은 차원을 알아서 할당함
print_obj(c, "c")

a:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

b:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

c:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]



In [117]:
# 퀴즈 15:  d=a.reshape((6, 4, -1)) 은 어떻게 나타나는가?
d = a.reshape((6, 4, -1))
print_obj(d, "d")

d:
[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]



In [119]:
e = a.reshape(-1,6)
print_obj(e, "e")

e:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]



- Python의 reshape()함수의 인자로 "-1"이 주어진 경우 최초 자료형의 원소의 갯수와 -1이 아닌 인자의 값을 이용하여 "-1"로 할당된 차원의 정확한 값이 추정된다.
- 설명만으로는 무슨 의미인지 불명확할 것이므로 c = a.reshape(6, -1)와 e = a.reshape(-1,6)의 출력 결과를 확인하여 보자.

In [120]:
# 추가적인 차원 더하기 (Adding an extra dimension_)
a = np.arange(3)
print_obj(a, "a")
## : 은 전부, 전부에다가 차원 하나 더 추가.
print_obj(a[:, None], "a[:, None]")

a:
[0 1 2]

a[:, None]:
[[0]
 [1]
 [2]]



In [124]:
# 퀴즈 16: a = np.ones((3,4))를 reshape와 None을 이용하여 (3, 1, 1, 4)의 shape로 변경해보기.
a = np.ones((3,4))
print_obj(a.reshape(3,1,1,4), "reshape")
print_obj(a[:, None, None, :], "None")

reshape:
[[[[1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]]]]

None:
[[[[1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]]]]



In [129]:
# 스택(Stack), concatenation (열 등을 이어서 연결하기)
# 스택은 쌓자!! h -> horizontal 수평  / v -> vertical 수직 ## 방향 주의
# 컨캣은 연결하자!! 축의 방향을 axis 로 설정해서 연결가능. 스택과 비슷한 기능.
## 중요!!!
a = np.ones((3,2))
b = np.zeros((3,2))
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.vstack([a, b]), "a,b vstack")
print_obj(np.hstack([a, b]), "a,b hstack")
print_obj(np.hstack([a, b, a]), "a,b,a hstack")

print_obj(np.concatenate([a, b], axis=0), "a,b concat axis=0")
print_obj(np.concatenate([a, b], axis=1), "a,b concat axis=1")

a:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

b:
[[0. 0.]
 [0. 0.]
 [0. 0.]]

a,b vstack:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

a,b hstack:
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]

a,b,a hstack:
[[1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1.]]

a,b concat axis=0:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

a,b concat axis=1:
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]



In [127]:
# 퀴즈 17: 두 텐서의 shape 가 (4, 3, 2) and (4, 3, 3) on axis=2 일 때, 두 텐서를 concatenation 하기.

a = np.ones((4, 3, 2))
b = np.ones((4, 3, 3))

np.concatenate([a, b], axis=2)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [130]:
print_obj(np.vstack([a, b]), "a,b vstack")
print_obj(np.vstack([a, b]).shape, "a,b vstack shape")
print_obj(np.vstack([a, b]).ndim, "a,b vstack ndim")
# 항상 텐서(행렬)의 크기와 모양을 잘 파악해서 데이터를 조작해야 한다.
# 차원의 크기를 파악하기 어려울 때는 이렇게 확인하거나 대괄호의 개수로 생각해보자.

a,b vstack:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

a,b vstack shape:
(6, 2)

a,b vstack ndim:
2



In [131]:
# 전치 행렬 (Matrix transpose)
a = np.arange(6).reshape((3, 2))
print_obj(a, "a")
# 손바닥 뒤집기!
print_obj(a.T, "a.T")

a:
[[0 1]
 [2 3]
 [4 5]]

a.T:
[[0 2 4]
 [1 3 5]]



$6\times 4$ 차원의 행렬을 전치 연산하면 $4\times 6$ 차원의 행렬이 된다.

$$
\begin{align}
X =
\begin{bmatrix}
\boxed{\begin{matrix} x_{1, 1} & x_{1, 2} & x_{1, 3} & x_{1, 4}\end{matrix}}  \\
\begin{matrix} x_{2, 1} & x_{2, 2} & x_{2, 3} & x_{2, 4}\end{matrix} \\
\begin{matrix} x_{3, 1} & x_{3, 2} & x_{3, 3} & x_{3, 4}\end{matrix} \\
\begin{matrix} x_{4, 1} & x_{4, 2} & x_{4, 3} & x_{4, 4}\end{matrix} \\
\begin{matrix} x_{5, 1} & x_{5, 2} & x_{5, 3} & x_{5, 4}\end{matrix} \\
\begin{matrix} x_{6, 1} & x_{6, 2} & x_{6, 3} & x_{6, 4}\end{matrix} \\
\end{bmatrix}
\;\; \rightarrow \;\;
X^T =
\begin{bmatrix}
\boxed{\begin{matrix} x_{1, 1} \\ x_{1, 2} \\ x_{1, 3} \\ x_{1, 4}\end{matrix}} &
\begin{matrix} x_{2, 1} \\ x_{2, 2} \\ x_{2, 3} \\ x_{2, 4}\end{matrix} &
\begin{matrix} x_{3, 1} \\ x_{3, 2} \\ x_{3, 3} \\ x_{3, 4}\end{matrix} &
\begin{matrix} x_{4, 1} \\ x_{4, 2} \\ x_{4, 3} \\ x_{4, 4}\end{matrix} &
\begin{matrix} x_{5, 1} \\ x_{5, 2} \\ x_{5, 3} \\ x_{5, 4}\end{matrix} &
\begin{matrix} x_{6, 1} \\ x_{6, 2} \\ x_{6, 3} \\ x_{6, 4}\end{matrix} &
\end{bmatrix}
\end{align}
$$

In [132]:
# 전치 텐서(Tensor transpose)
a = np.arange(24).reshape((4, 3, 2))
print_obj(a, "a")
# T ~~ transpose 전치 같은 기능.
b = np.transpose(a, [0, 2, 1])  ## T랑 똑같다.
print_obj(b, "Swap axis 1 and 2")
print_obj(b.shape, "b's shape")

c = np.transpose(a, [1, 0, 2])
print_obj(c, "Swap axis 0 and 1")
print_obj(c.shape, "c's shape")

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

Swap axis 1 and 2:
[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]

b's shape:
(4, 2, 3)

Swap axis 0 and 1:
[[[ 0  1]
  [ 6  7]
  [12 13]
  [18 19]]

 [[ 2  3]
  [ 8  9]
  [14 15]
  [20 21]]

 [[ 4  5]
  [10 11]
  [16 17]
  [22 23]]]

c's shape:
(3, 4, 2)



### 브로드캐스팅(Broadcasting)

<figure>
    <img src="http://www.astroml.org/_images/fig_broadcast_visual_1.png">
</figure>

In [133]:
# Vector and scalar
a = np.arange(3)
b = 2.

## 자동으로 공란을 채워서 연산을 수행하는 기능 ## 파이썬의 특성!!
# 벡터랑 스칼라 끼리. 연산이 가능하다.
print_obj(a, "a")
print_obj(b, "b")
print_obj(a+b, "a+b")
print_obj(a-b, "a-b")
print_obj(a*b, "a*b")
print_obj(a/b, "a/b")

a:
[0 1 2]

b:
2.0

a+b:
[2. 3. 4.]

a-b:
[-2. -1.  0.]

a*b:
[0. 2. 4.]

a/b:
[0.  0.5 1. ]



In [134]:
# 행렬과 벡터 (Matrix and vector)
a = np.arange(6).reshape((3,2))
b = np.arange(2).reshape(2) + 1
print_obj(a, "a")
print_obj(b, "b")

print_obj(a+b, "a+b")


a:
[[0 1]
 [2 3]
 [4 5]]

b:
[1 2]

a+b:
[[1 3]
 [3 5]
 [5 7]]



In [135]:
# 텐서와 행렬 (Tensor and matrix)
a = np.arange(12).reshape((2,3,2))
b = np.arange(6).reshape((3,2))
print_obj(a, "a")
print_obj(b, "b")

print_obj(a+b, "a+b")



a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

b:
[[0 1]
 [2 3]
 [4 5]]

a+b:
[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[ 6  8]
  [10 12]
  [14 16]]]

